In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
arr1= np.array([[4,5,6],[7,8,9],[10,11,12]])

In [7]:
arr1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr2 = np.array([[5,6,4,4,5,6,5],[8,9,7,7,8, 9,8],[11,12,10,10,11,12,11]])

In [9]:
arr2

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

In [10]:
arr3 = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])

In [11]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr4 = np.flip(arr3,axis=1)

In [15]:
arr4

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [17]:
arr5 = np.arange(3)
arr6 = np.arange(3,7)
arr7 = np.arange(7,10)

array_of_arrays = np.array([arr5, arr6, arr7])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [18]:
new_arr = np.concatenate((arr5,arr6,arr7),axis=0)

In [19]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])